version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - "8080:80"
  
  backend:
      build: 
        context: ./backendFlask
        dockerfile: ./Dockerfile
      working_dir: /app
      ports:
        - "80:80"
        - "5000:5000"